config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'following_user' => 'relationships#following_user', as: 'following_user'
    get 'follower_user' => 'relationships#follower_user', as: 'follower_user'
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followeds
    @user = User.find(params[:id])
    @followeds = @user.followed_users
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_users
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, format: 'jpg', size: "100x100", fallback: "ikko.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th>introduction</th>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <th>follows</th>
        <td>
          <%= link_to user_following_user_path(user) do %>
            <%= user.follower.count %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>followers</th>
        <td>
          <%= link_to user_follower_user_path(user) do %>
            <%= user.followed.count %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <% if current_user == user %>
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block btn-sm" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', user_relationships_path(user.id), class: "btn btn-info", method: :delete %>
        <% if user.following?(current_user) %>
          <% if @isRoom == true %>
            <%= link_to 'チャットへ', room_path(@roomId), class: "btn btn-primary" %>
          <% else %>
            <%= form_with model: @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, :value => @user.id %>
              <% end %>
              <%= f.submit "chatを始める", class: "btn btn-primary" %>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to 'フォローする', user_relationships_path(user.id), class: "btn btn-success", method: :post %>
      <% end %>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book, local:true do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create book', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div class="error_explanation">
          <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: 'form-control', autofocus: true %>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.attachment_field :profile_image, class: 'form-control-file'%>
      </div>
      <div class="form-group">
        <label>Introduction</label>
        <%= f.text_area :introduction, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: 'btn btn-secondary' %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-3 px-sm-0">
  <div class="row">
    <%= render 'users/user_info', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="image-width">
                <%= link_to user_path(user.id) do %>
                  <%= attachment_image_tag user, :profile_image, format: 'jpg', size: "40x40", fallback: "ikko.jpg" %>
                <% end %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>フォロー数： <%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
              <td>
                <% if current_user != user %>
                  <% if current_user.following?(user) %>
                    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to 'Show' ,user_path(user.id) %>
              </td>
            </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-3 px-sm-0">
  <div class="row">
    <%= render 'users/user_info', user: @user, book: @book %>
    <%= render 'books/book_list', books: @books %>
  </div>
</div>